[package]
name = "blockchain_fundamentals"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
sha3 = { workspace = true }

[[bin]]
name = "block"
path = "src/01_block.rs"

[[bin]]
name = "transaction"
path = "src/02_transaction.rs"

[[bin]]
name = "account"
path = "src/03_account.rs"

[[bin]]
name = "address"
path = "src/04_address.rs"

[[bin]]
name = "confirmation"
path = "src/05_confirmation.rs"

[[bin]]
name = "finality"
path = "src/06_finality.rs"
